# Generated by Django 5.1.4 on 2024-12-18 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
